id = "ohtml"
name = "OHTML"
version = "0.2.0"
schema_version = 1
authors = ["Ankit Patial"]
description = "Odin HTML template language support with syntax highlighting, diagnostics, and completions"
repository = "https://github.com/ankitpatial/odin-html"

[language_servers.ohtml-lsp]
name = "OHTML LSP"
language = "OHTML"

[grammars.ohtml]
repository = "https://github.com/ankitpatial/odin-html"
rev = "main"
path = "tree-sitter-ohtml"
