// src/runtime_gen/runtime_gen.odin
package rt_gen

import "core:os"
import "core:strings"

GENERATED_HEADER :: "// Code generated by ohtml. DO NOT EDIT.\n"

ESCAPE_ODIN :: `// Code generated by ohtml. DO NOT EDIT.
package rt

import "core:io"
import "core:unicode/utf8"

html_escape :: proc(w: io.Writer, s: string) {
    for r in s {
        switch r {
        case '&':  io.write_string(w, "&amp;")
        case '<':  io.write_string(w, "&lt;")
        case '>':  io.write_string(w, "&gt;")
        case '"':  io.write_string(w, "&quot;")
        case '\'': io.write_string(w, "&#39;")
        case:
            buf: [4]u8
            n := utf8.encode_rune(buf[:], r)
            io.write(w, buf[:n])
        }
    }
}
`

SNIPPET_ODIN :: `// Code generated by ohtml. DO NOT EDIT.
package rt

import "core:io"

Children :: struct {
    func: proc(w: io.Writer, ctx: rawptr),
    ctx: rawptr,
}

children_render :: proc(w: io.Writer, c: Children) {
    if c.func != nil {
        c.func(w, c.ctx)
    }
}

Snippet :: struct($T: typeid) {
    func: proc(w: io.Writer, ctx: rawptr, arg: T),
    ctx: rawptr,
}

snippet_render :: proc($T: typeid, w: io.Writer, s: Snippet(T), arg: T) {
    if s.func != nil {
        s.func(w, s.ctx, arg)
    }
}
`

generate :: proc(out_dir: string) -> bool {
    runtime_dir := strings.concatenate({out_dir, "/rt"})
    os.make_directory(runtime_dir)
    if !write_escape(runtime_dir) { return false }
    if !write_snippet(runtime_dir) { return false }
    return true
}

write_escape :: proc(runtime_dir: string) -> bool {
    path := strings.concatenate({runtime_dir, "/escape.odin"})
    err := os.write_entire_file(path, transmute([]byte)string(ESCAPE_ODIN))
    return err == nil
}

write_snippet :: proc(runtime_dir: string) -> bool {
    path := strings.concatenate({runtime_dir, "/snippet.odin"})
    err := os.write_entire_file(path, transmute([]byte)string(SNIPPET_ODIN))
    return err == nil
}
