// src/codegen/codegen.odin
package codegen

import "core:strings"
import "core:fmt"
import "../ast"

// ─── state ────────────────────────────────────────────────────────────────────

Generator :: struct {
    b:               strings.Builder,
    // imports
    need_fmt:        bool,
    need_rt:    bool,
    // scope stack: each entry is a set of local variable names
    scopes:          [dynamic]map[string]bool,
    // counters for unique child/snippet proc names
    child_counter:   int,
    // top-level procs/structs that need to be emitted before render
    preamble:        strings.Builder,
    // props lookup for type resolution
    props_fields:    map[string]string, // name -> type_expr
    // snippet fields (name -> arg_type or "")
    snippet_fields:  map[string]string,
    // indentation level
    indent:          int,
    // When non-nil, {@render children()} emits this pre-generated content instead
    // of the normal rt.children_render call. Used for layout inlining.
    layout_children_content: Maybe(string),
    // When true, whitespace in Text nodes is preserved exactly (inside <pre>/<code>)
    preserve_whitespace: bool,
}

// ─── entry points ─────────────────────────────────────────────────────────────

generate :: proc(doc: ast.Document, pkg_name: string) -> string {
    return generate_page(doc, pkg_name, nil)
}

generate_page :: proc(doc: ast.Document, pkg_name: string, layout_chain: []ast.Document) -> string {
    g := Generator{}
    strings.builder_init(&g.b)
    strings.builder_init(&g.preamble)
    g.scopes = make([dynamic]map[string]bool)
    g.props_fields = make(map[string]string)
    g.snippet_fields = make(map[string]string)

    // Build props_fields and snippet_fields lookup
    if script, ok := doc.script.?; ok {
        if props_def, ok2 := script.props.?; ok2 {
            for field in props_def.fields {
                g.props_fields[field.name] = field.type_expr
                if field.is_snippet {
                    if arg_type, ok3 := field.snippet_arg_type.?; ok3 {
                        g.snippet_fields[field.name] = arg_type
                    } else {
                        g.snippet_fields[field.name] = ""
                    }
                }
            }
        }
    }

    // Scan children for component usages - we need preamble for snippet call sites
    // (this is a two-pass approach: first collect preamble, then emit body)
    // We'll do it inline and collect preamble separately

    // Generate body first into a temp builder, then assemble
    body_b := strings.Builder{}
    strings.builder_init(&body_b)

    // generate render body
    has_props := false
    if script, ok := doc.script.?; ok {
        if _, ok2 := script.props.?; ok2 {
            has_props = true
        }
    }

    // Push global scope (no local vars at top level)
    push_scope(&g)

    // Generate nodes into body
    g.indent = 1

    // If we have a layout chain, inline layouts around the page content.
    // layout_chain is ordered outermost to innermost.
    // We emit: layout[0].before + layout[1].before + ... + page + ... + layout[1].after + layout[0].after
    if layout_chain != nil && len(layout_chain) > 0 {
        gen_layout_inlined(&g, doc.children[:], layout_chain, &g.b)
    } else {
        for node in doc.children {
            gen_node(&g, node, &g.b)
        }
    }

    pop_scope(&g)

    // Now assemble the full file
    out := strings.Builder{}
    strings.builder_init(&out)

    // Header
    strings.write_string(&out, "// Code generated by ohtml. DO NOT EDIT.\n")
    fmt.sbprintf(&out, "package %s\n\n", pkg_name)

    // Imports
    strings.write_string(&out, `import "core:io"`)
    strings.write_string(&out, "\n")
    if g.need_fmt {
        strings.write_string(&out, `import "core:fmt"`)
        strings.write_string(&out, "\n")
    }
    if g.need_rt {
        strings.write_string(&out, `import rt "gen/rt"`)
        strings.write_string(&out, "\n")
    }

    // User imports from script block
    if script, ok := doc.script.?; ok {
        for imp in script.imports {
            if alias, ok2 := imp.alias.?; ok2 {
                fmt.sbprintf(&out, "import %s \"%s\"\n", alias, imp.path)
            } else {
                fmt.sbprintf(&out, "import \"%s\"\n", imp.path)
            }
        }
    }

    strings.write_string(&out, "\n")

    // Props struct (rewritten with runtime types)
    if script, ok := doc.script.?; ok {
        if props_def, ok2 := script.props.?; ok2 {
            strings.write_string(&out, "Props :: struct {\n")
            for field in props_def.fields {
                if field.is_snippet {
                    if arg_type, ok3 := field.snippet_arg_type.?; ok3 {
                        fmt.sbprintf(&out, "    %s: rt.Snippet(%s),\n", field.name, arg_type)
                    } else {
                        fmt.sbprintf(&out, "    %s: rt.Children,\n", field.name)
                    }
                } else {
                    fmt.sbprintf(&out, "    %s: %s,\n", field.name, field.type_expr)
                }
            }
            strings.write_string(&out, "}\n\n")
        }
    }

    // Preamble (helper structs/procs for component children)
    preamble_str := strings.to_string(g.preamble)
    if len(preamble_str) > 0 {
        strings.write_string(&out, preamble_str)
        strings.write_string(&out, "\n")
    }

    // render proc signature
    if has_props {
        strings.write_string(&out, "render :: proc(w: io.Writer, props: Props) {\n")
    } else {
        strings.write_string(&out, "render :: proc(w: io.Writer) {\n")
    }

    // Body
    strings.write_string(&out, strings.to_string(g.b))

    strings.write_string(&out, "}\n")

    return strings.to_string(out)
}

// ─── scope helpers ────────────────────────────────────────────────────────────

push_scope :: proc(g: ^Generator) {
    scope := make(map[string]bool)
    append(&g.scopes, scope)
}

pop_scope :: proc(g: ^Generator) {
    if len(g.scopes) > 0 {
        scope := g.scopes[len(g.scopes)-1]
        delete(scope)
        resize(&g.scopes, len(g.scopes)-1)
    }
}

add_to_scope :: proc(g: ^Generator, name: string) {
    if len(g.scopes) > 0 {
        g.scopes[len(g.scopes)-1][name] = true
    }
}

is_in_scope :: proc(g: ^Generator, name: string) -> bool {
    // Walk from top of stack downward
    for i := len(g.scopes) - 1; i >= 0; i -= 1 {
        if g.scopes[i][name] {
            return true
        }
    }
    return false
}

// ─── indent helpers ───────────────────────────────────────────────────────────

write_indent :: proc(g: ^Generator, b: ^strings.Builder) {
    for i := 0; i < g.indent; i += 1 {
        strings.write_string(b, "    ")
    }
}

// ─── resolve expression name ──────────────────────────────────────────────────

// Given an expression like "name" or "item.name" or "props.foo",
// determine if the root identifier is in local scope or a props field,
// and return the properly prefixed expression.
resolve_expr :: proc(g: ^Generator, expr: string) -> string {
    trimmed := strings.trim_space(expr)
    // Find the root identifier (before any dot or bracket)
    dot_idx := strings.index(trimmed, ".")
    root := trimmed
    if dot_idx >= 0 {
        root = trimmed[:dot_idx]
    }
    root = strings.trim_space(root)

    if is_in_scope(g, root) {
        return trimmed
    }
    // It's a props field
    return strings.concatenate({"props.", trimmed})
}

// Get the type of a props field. Returns "" if not found.
props_field_type :: proc(g: ^Generator, name: string) -> string {
    if t, ok := g.props_fields[name]; ok {
        return t
    }
    return ""
}

// ─── HTML string collapsing ───────────────────────────────────────────────────

// flush_static emits a pending static buffer as an io.write_string call
flush_static :: proc(g: ^Generator, buf: ^strings.Builder, b: ^strings.Builder) {
    s := strings.to_string(buf^)
    if len(s) > 0 {
        write_indent(g, b)
        fmt.sbprintf(b, "io.write_string(w, %q)\n", s)
        strings.builder_reset(buf)
    }
}

// Generates a list of nodes, collapsing adjacent static text into single io.write_string calls
gen_nodes :: proc(g: ^Generator, nodes: []ast.Node, b: ^strings.Builder) {
    static_buf := strings.Builder{}
    strings.builder_init(&static_buf)

    for node in nodes {
        switch n in node {
        case ast.Text:
            if !g.preserve_whitespace && strings.trim_space(n.content) == "" {
                // Pure-whitespace inter-element text: collapse to nothing
                // (omit to avoid emitting raw newlines/spaces between tags)
            } else {
                strings.write_string(&static_buf, n.content)
            }
        case ast.Element:
            // Check if the entire element (attrs + children) is static BEFORE writing anything
            if are_element_static(n) {
                // Fully static: accumulate into static_buf
                gen_element_static_open(&static_buf, n)
                if !n.self_close {
                    // Preserve whitespace inside <pre> and <code>
                    child_preserve := g.preserve_whitespace || n.tag == "pre" || n.tag == "code"
                    gen_nodes_static(&static_buf, n.children[:], child_preserve)
                    gen_element_close(&static_buf, n.tag)
                }
            } else {
                // Has dynamic attrs or dynamic children: flush static so far, go dynamic
                flush_static(g, &static_buf, b)
                gen_element_open_dynamic(g, n, b)
                if !n.self_close {
                    // Preserve whitespace inside <pre> and <code>
                    old_preserve := g.preserve_whitespace
                    if n.tag == "pre" || n.tag == "code" {
                        g.preserve_whitespace = true
                    }
                    gen_nodes(g, n.children[:], b)
                    g.preserve_whitespace = old_preserve
                    // Close tag goes into static_buf for potential collapsing
                    gen_element_close(&static_buf, n.tag)
                }
            }
        case ast.Expression:
            flush_static(g, &static_buf, b)
            gen_expression(g, n, b)
        case ast.Raw_Html:
            flush_static(g, &static_buf, b)
            gen_raw_html(g, n, b)
        case ast.If_Block:
            flush_static(g, &static_buf, b)
            gen_if_block(g, n, b)
        case ast.Each_Block:
            flush_static(g, &static_buf, b)
            gen_each_block(g, n, b)
        case ast.Snippet_Def:
            flush_static(g, &static_buf, b)
            gen_snippet_def(g, n, b)
        case ast.Render_Call:
            flush_static(g, &static_buf, b)
            gen_render_call(g, n, b)
        case ast.Component:
            flush_static(g, &static_buf, b)
            gen_component(g, n, b)
        }
    }
    flush_static(g, &static_buf, b)
}

// gen_node generates a single node
gen_node :: proc(g: ^Generator, node: ast.Node, b: ^strings.Builder) {
    nodes := [1]ast.Node{node}
    gen_nodes(g, nodes[:], b)
}

// Check if all nodes are purely static (no expressions, control flow, etc.)
are_all_static :: proc(nodes: []ast.Node) -> bool {
    for node in nodes {
        switch n in node {
        case ast.Text:
            // static
        case ast.Element:
            if !are_element_static(n) { return false }
        case ast.Raw_Html:
            // Literal Raw_Html (e.g. DOCTYPE) is static; expression Raw_Html is not
            if !n.is_literal { return false }
        case ast.Expression, ast.If_Block, ast.Each_Block,
             ast.Snippet_Def, ast.Render_Call, ast.Component:
            return false
        }
    }
    return true
}

are_element_static :: proc(el: ast.Element) -> bool {
    // Check attrs for dynamic
    for attr in el.attributes {
        switch _ in attr.value {
        case ast.Static_Value:
            // ok
        case ast.Dynamic_Value, ast.Bool_Shorthand:
            return false
        }
    }
    return are_all_static(el.children[:])
}

// ─── static element generation ────────────────────────────────────────────────

// Write element opening tag to a static buffer (no dynamic checks)
gen_element_static_open :: proc(buf: ^strings.Builder, el: ast.Element) {
    fmt.sbprintf(buf, "<%s", el.tag)
    for attr in el.attributes {
        switch v in attr.value {
        case ast.Static_Value:
            fmt.sbprintf(buf, " %s=\"%s\"", attr.name, v.value)
        case ast.Dynamic_Value:
            // Shouldn't be called for static elements
        case ast.Bool_Shorthand:
            // Shouldn't be called for static elements
        }
    }
    if el.self_close {
        strings.write_string(buf, "/>")
    } else {
        strings.write_string(buf, ">")
    }
}

gen_element_close :: proc(buf: ^strings.Builder, tag: string) {
    fmt.sbprintf(buf, "</%s>", tag)
}

// Write static content of nodes into a static buffer.
// preserve_ws: when true, write text exactly; when false, collapse pure-whitespace text.
gen_nodes_static :: proc(buf: ^strings.Builder, nodes: []ast.Node, preserve_ws: bool = false) {
    for node in nodes {
        switch n in node {
        case ast.Text:
            if !preserve_ws && strings.trim_space(n.content) == "" {
                // Collapse pure-whitespace inter-element text
            } else {
                strings.write_string(buf, n.content)
            }
        case ast.Element:
            gen_element_static_open(buf, n)
            if !n.self_close {
                child_preserve := preserve_ws || n.tag == "pre" || n.tag == "code"
                gen_nodes_static(buf, n.children[:], child_preserve)
                gen_element_close(buf, n.tag)
            }
        case ast.Raw_Html:
            // Literal Raw_Html nodes (e.g. DOCTYPE) can appear in static contexts
            if n.is_literal {
                strings.write_string(buf, n.content)
            }
            // Non-literal (expression) Raw_Html should not appear in static context
        case ast.Expression, ast.If_Block, ast.Each_Block,
             ast.Snippet_Def, ast.Render_Call, ast.Component:
            // Should not happen in static context
        }
    }
}

// ─── dynamic element generation ───────────────────────────────────────────────

// Emit dynamic open tag (already flushed static, so write directly to b)
gen_element_open_dynamic :: proc(g: ^Generator, el: ast.Element, b: ^strings.Builder) {
    // Collect static prefix of the open tag
    static_prefix := strings.Builder{}
    strings.builder_init(&static_prefix)
    fmt.sbprintf(&static_prefix, "<%s", el.tag)

    for attr in el.attributes {
        switch v in attr.value {
        case ast.Static_Value:
            fmt.sbprintf(&static_prefix, " %s=\"%s\"", attr.name, v.value)
        case ast.Dynamic_Value:
            // Determine type first
            dv_dot_idx := strings.index(v.expr, ".")
            dv_root := strings.trim_space(v.expr)
            if dv_dot_idx >= 0 {
                dv_root = strings.trim_space(v.expr[:dv_dot_idx])
            }
            dv_field_type := ""
            if !is_in_scope(g, dv_root) {
                dv_field_type = props_field_type(g, dv_root)
            }
            dv_expr := resolve_expr(g, v.expr)

            if dv_field_type == "bool" {
                // Bool attribute: flush prefix, emit if block (no "name=")
                prefix := strings.to_string(static_prefix)
                if len(prefix) > 0 {
                    write_indent(g, b)
                    fmt.sbprintf(b, "io.write_string(w, %q)\n", prefix)
                    strings.builder_reset(&static_prefix)
                }
                write_indent(g, b)
                fmt.sbprintf(b, "if %s {{\n", dv_expr)
                g.indent += 1
                write_indent(g, b)
                fmt.sbprintf(b, "io.write_string(w, \" %s\")\n", attr.name)
                g.indent -= 1
                write_indent(g, b)
                strings.write_string(b, "}\n")
            } else {
                // Regular dynamic attribute: flush prefix, emit name=, value, closing quote
                prefix := strings.to_string(static_prefix)
                if len(prefix) > 0 {
                    write_indent(g, b)
                    fmt.sbprintf(b, "io.write_string(w, %q)\n", prefix)
                    strings.builder_reset(&static_prefix)
                }
                write_indent(g, b)
                fmt.sbprintf(b, "io.write_string(w, %q)\n", fmt.tprintf(" %s=\"", attr.name))
                g.need_rt = true
                if dv_field_type == "string" {
                    write_indent(g, b)
                    fmt.sbprintf(b, "rt.html_escape(w, %s)\n", dv_expr)
                } else {
                    g.need_fmt = true
                    write_indent(g, b)
                    fmt.sbprintf(b, "rt.html_escape(w, fmt.tprint(%s))\n", dv_expr)
                }
                write_indent(g, b)
                strings.write_string(b, "io.write_string(w, \"\\\"\")\n")
            }
        case ast.Bool_Shorthand:
            // Flush static prefix
            prefix := strings.to_string(static_prefix)
            if len(prefix) > 0 {
                write_indent(g, b)
                fmt.sbprintf(b, "io.write_string(w, %q)\n", prefix)
                strings.builder_reset(&static_prefix)
            }
            // Boolean attribute: if props.disabled { io.write_string(w, " disabled") }
            expr := resolve_expr(g, attr.name)
            write_indent(g, b)
            fmt.sbprintf(b, "if %s {{\n", expr)
            g.indent += 1
            write_indent(g, b)
            fmt.sbprintf(b, "io.write_string(w, \" %s\")\n", attr.name)
            g.indent -= 1
            write_indent(g, b)
            strings.write_string(b, "}\n")
        }
    }

    // Flush remaining static prefix + ">"
    if el.self_close {
        strings.write_string(&static_prefix, "/>")
    } else {
        strings.write_string(&static_prefix, ">")
    }
    prefix := strings.to_string(static_prefix)
    if len(prefix) > 0 {
        write_indent(g, b)
        fmt.sbprintf(b, "io.write_string(w, %q)\n", prefix)
    }
}

// ─── expression ───────────────────────────────────────────────────────────────

gen_expression :: proc(g: ^Generator, expr: ast.Expression, b: ^strings.Builder) {
    content := strings.trim_space(expr.content)

    // Resolve root name for type lookup
    dot_idx := strings.index(content, ".")
    root_name := content
    if dot_idx >= 0 {
        root_name = content[:dot_idx]
    }
    root_name = strings.trim_space(root_name)

    resolved := resolve_expr(g, content)
    g.need_rt = true

    // Determine type
    field_type := ""
    if !is_in_scope(g, root_name) {
        field_type = props_field_type(g, root_name)
    }

    if field_type == "string" {
        write_indent(g, b)
        fmt.sbprintf(b, "rt.html_escape(w, %s)\n", resolved)
    } else {
        // Non-string: use fmt.tprint
        g.need_fmt = true
        write_indent(g, b)
        fmt.sbprintf(b, "rt.html_escape(w, fmt.tprint(%s))\n", resolved)
    }
}

// ─── raw html ─────────────────────────────────────────────────────────────────

gen_raw_html :: proc(g: ^Generator, raw: ast.Raw_Html, b: ^strings.Builder) {
    content := strings.trim_space(raw.content)
    write_indent(g, b)
    if raw.is_literal {
        // Literal HTML content (e.g. <!DOCTYPE html>) — emit as a quoted string literal
        fmt.sbprintf(b, "io.write_string(w, %q)\n", content)
    } else {
        // Expression variable (e.g. {@html my_var}) — resolve and emit as identifier
        resolved := resolve_expr(g, content)
        fmt.sbprintf(b, "io.write_string(w, %s)\n", resolved)
    }
}

// ─── if block ─────────────────────────────────────────────────────────────────

gen_if_block :: proc(g: ^Generator, ib: ast.If_Block, b: ^strings.Builder) {
    condition := resolve_expr(g, ib.condition)
    write_indent(g, b)
    fmt.sbprintf(b, "if %s {{\n", condition)
    g.indent += 1
    push_scope(g)
    gen_nodes(g, ib.children[:], b)
    pop_scope(g)
    g.indent -= 1

    for else_if in ib.else_ifs {
        write_indent(g, b)
        ei_cond := resolve_expr(g, else_if.condition)
        fmt.sbprintf(b, "}} else if %s {{\n", ei_cond)
        g.indent += 1
        push_scope(g)
        gen_nodes(g, else_if.children[:], b)
        pop_scope(g)
        g.indent -= 1
    }

    if else_body, ok := ib.else_body.?; ok {
        write_indent(g, b)
        strings.write_string(b, "} else {\n")
        g.indent += 1
        push_scope(g)
        gen_nodes(g, else_body[:], b)
        pop_scope(g)
        g.indent -= 1
    }

    write_indent(g, b)
    strings.write_string(b, "}\n")
}

// ─── each block ───────────────────────────────────────────────────────────────

gen_each_block :: proc(g: ^Generator, eb: ast.Each_Block, b: ^strings.Builder) {
    iterable := resolve_expr(g, eb.iterable)

    if else_body, ok := eb.else_body.?; ok {
        // Wrap with len check
        write_indent(g, b)
        fmt.sbprintf(b, "if len(%s) > 0 {{\n", iterable)
        g.indent += 1
        gen_each_loop(g, eb, iterable, b)
        g.indent -= 1
        write_indent(g, b)
        strings.write_string(b, "} else {\n")
        g.indent += 1
        push_scope(g)
        gen_nodes(g, else_body[:], b)
        pop_scope(g)
        g.indent -= 1
        write_indent(g, b)
        strings.write_string(b, "}\n")
    } else {
        gen_each_loop(g, eb, iterable, b)
    }
}

gen_each_loop :: proc(g: ^Generator, eb: ast.Each_Block, iterable: string, b: ^strings.Builder) {
    if index, ok := eb.index.?; ok {
        write_indent(g, b)
        // Odin: for value, index in collection
        fmt.sbprintf(b, "for %s, %s in %s {{\n", eb.binding, index, iterable)
    } else {
        write_indent(g, b)
        fmt.sbprintf(b, "for %s in %s {{\n", eb.binding, iterable)
    }
    g.indent += 1
    push_scope(g)
    add_to_scope(g, eb.binding)
    if index, ok := eb.index.?; ok {
        add_to_scope(g, index)
    }
    gen_nodes(g, eb.children[:], b)
    pop_scope(g)
    g.indent -= 1
    write_indent(g, b)
    strings.write_string(b, "}\n")
}

// ─── snippet def ──────────────────────────────────────────────────────────────

gen_snippet_def :: proc(g: ^Generator, sd: ast.Snippet_Def, b: ^strings.Builder) {
    // Inline snippet definition - generate a proc for it
    // This is used when a Component contains {#snippet row(item: Item)}...{/snippet}
    // We generate it into preamble
    idx := g.child_counter
    g.child_counter += 1

    param_name := ""
    param_type := ""
    if pn, ok := sd.param_name.?; ok {
        param_name = pn
    }
    if pt, ok := sd.param_type.?; ok {
        param_type = pt
    }

    proc_name := fmt.tprintf("_%s_%s_%d_render", sd.name, sd.name, idx)

    // Generate the snippet render proc into preamble
    if len(param_type) > 0 {
        fmt.sbprintf(&g.preamble, "%s :: proc(w: io.Writer, ctx_ptr: rawptr, arg: %s) {{\n", proc_name, param_type)
    } else {
        fmt.sbprintf(&g.preamble, "%s :: proc(w: io.Writer, ctx_ptr: rawptr) {{\n", proc_name)
    }
    g.indent = 1

    old_b := g.b
    g.b = strings.Builder{}
    strings.builder_init(&g.b)

    push_scope(g)
    if len(param_name) > 0 {
        add_to_scope(g, param_name)
    }
    gen_nodes(g, sd.children[:], &g.b)
    pop_scope(g)

    strings.write_string(&g.preamble, strings.to_string(g.b))
    g.b = old_b

    strings.write_string(&g.preamble, "}\n\n")
    g.indent = 1

    // Emit the snippet binding in place (inline in render body)
    _ = idx
}

// ─── render call ──────────────────────────────────────────────────────────────

gen_render_call :: proc(g: ^Generator, rc: ast.Render_Call, b: ^strings.Builder) {
    name := rc.name

    // Layout inlining: if this is a {@render children()} and we have injected content, emit it directly.
    if name == "children" {
        if content, ok := g.layout_children_content.?; ok {
            strings.write_string(b, content)
            return
        }
    }

    g.need_rt = true

    // Check if it's a children call (no args or explicit children())
    if snippet_arg_type, ok := g.snippet_fields[name]; ok {
        if len(snippet_arg_type) == 0 {
            // children: rt.Children
            write_indent(g, b)
            fmt.sbprintf(b, "rt.children_render(w, props.%s)\n", name)
        } else {
            // typed snippet
            if args_val, ok2 := rc.args.?; ok2 {
                arg := resolve_expr(g, strings.trim_space(args_val))
                write_indent(g, b)
                fmt.sbprintf(b, "rt.snippet_render(%s, w, props.%s, %s)\n", snippet_arg_type, name, arg)
            } else {
                write_indent(g, b)
                fmt.sbprintf(b, "rt.snippet_render(%s, w, props.%s)\n", snippet_arg_type, name)
            }
        }
    } else {
        // Not a known snippet field — could be a local snippet var
        if args_val, ok := rc.args.?; ok {
            arg := resolve_expr(g, strings.trim_space(args_val))
            write_indent(g, b)
            fmt.sbprintf(b, "rt.snippet_render(_, w, %s, %s)\n", name, arg)
        } else {
            write_indent(g, b)
            fmt.sbprintf(b, "rt.children_render(w, %s)\n", name)
        }
    }
}

// ─── component ────────────────────────────────────────────────────────────────

gen_component :: proc(g: ^Generator, comp: ast.Component, b: ^strings.Builder) {
    idx := g.child_counter
    g.child_counter += 1

    pkg := strings.to_lower(comp.pkg)
    comp_lower := strings.to_lower(comp.name)

    // Collect variables referenced in children for the ctx struct
    refs := collect_var_refs(g, comp.children[:])

    has_children := len(comp.children) > 0
    // Separate snippet defs from non-snippet children
    snippet_defs: [dynamic]ast.Snippet_Def
    non_snippet_children: [dynamic]ast.Node

    for child in comp.children {
        if sd, ok := child.(ast.Snippet_Def); ok {
            append(&snippet_defs, sd)
        } else {
            append(&non_snippet_children, child)
        }
    }

    has_non_snippet := len(non_snippet_children) > 0
    has_snippet_defs := len(snippet_defs) > 0

    // Generate children render proc and ctx struct if needed
    if has_non_snippet {
        ctx_name := fmt.tprintf("_%s_%s_%d_ctx", pkg, comp_lower, idx)
        render_name := fmt.tprintf("_%s_%s_%d_render", pkg, comp_lower, idx)

        // Ctx struct
        fmt.sbprintf(&g.preamble, "%s :: struct {{\n", ctx_name)
        for ref in refs {
            field_type := props_field_type(g, ref)
            if len(field_type) == 0 { field_type = "rawptr" }
            fmt.sbprintf(&g.preamble, "    %s: %s,\n", ref, field_type)
        }
        strings.write_string(&g.preamble, "}\n\n")

        // Render proc
        fmt.sbprintf(&g.preamble, "%s :: proc(w: io.Writer, ctx_ptr: rawptr) {{\n", render_name)
        fmt.sbprintf(&g.preamble, "    ctx := (^%s)(ctx_ptr)\n", ctx_name)

        // Generate children body with ctx.xxx references
        old_b := g.b
        old_indent := g.indent
        g.b = strings.Builder{}
        strings.builder_init(&g.b)
        g.indent = 1

        // Temporarily modify scope to use ctx. prefix
        push_scope(g)
        for ref in refs {
            add_to_scope(g, ref)  // mark as local so resolve_expr won't add props.
        }

        // Store refs for ctx generation
        old_props := g.props_fields
        ctx_props := make(map[string]string)
        for ref in refs {
            field_type := props_field_type(g, ref)
            ctx_props[ref] = field_type
        }
        // Override: when in ctx scope, expressions referencing outer vars should use ctx.xxx
        ctx_gen := g
        _ = ctx_gen
        gen_nodes_with_ctx(g, non_snippet_children[:], &g.b, refs, ctx_name)

        strings.write_string(&g.preamble, strings.to_string(g.b))
        g.b = old_b
        g.indent = old_indent
        pop_scope(g)
        g.props_fields = old_props

        strings.write_string(&g.preamble, "}\n\n")

        // In the render body: declare ctx, call component
        write_indent(g, b)
        fmt.sbprintf(b, "_ctx_%d := %s{{\n", idx, ctx_name)
        for ref in refs {
            write_indent(g, b)
            fmt.sbprintf(b, "    %s = props.%s,\n", ref, ref)
        }
        write_indent(g, b)
        strings.write_string(b, "}\n")

        // Call component render
        write_indent(g, b)
        if len(pkg) > 0 {
            fmt.sbprintf(b, "%s.render(w, %s.Props{{\n", pkg, pkg)
        } else {
            fmt.sbprintf(b, "render(w, Props{{\n")
        }

        // Attributes
        for attr in comp.attributes {
            write_indent(g, b)
            switch v in attr.value {
            case ast.Static_Value:
                fmt.sbprintf(b, "    %s = \"%s\",\n", attr.name, v.value)
            case ast.Dynamic_Value:
                expr := resolve_expr(g, v.expr)
                fmt.sbprintf(b, "    %s = %s,\n", attr.name, expr)
            case ast.Bool_Shorthand:
                fmt.sbprintf(b, "    %s = true,\n", attr.name)
            }
        }

        // Children field
        write_indent(g, b)
        g.need_rt = true
        fmt.sbprintf(b, "    children = rt.Children{{\n")
        write_indent(g, b)
        fmt.sbprintf(b, "        func = %s,\n", render_name)
        write_indent(g, b)
        fmt.sbprintf(b, "        ctx = &_ctx_%d,\n", idx)
        write_indent(g, b)
        strings.write_string(b, "    },\n")

        write_indent(g, b)
        strings.write_string(b, "})\n")

    } else if has_snippet_defs {
        // Only snippet defs as children
        write_indent(g, b)
        if len(pkg) > 0 {
            fmt.sbprintf(b, "%s.render(w, %s.Props{{\n", pkg, pkg)
        } else {
            fmt.sbprintf(b, "render(w, Props{{\n")
        }
        for attr in comp.attributes {
            write_indent(g, b)
            switch v in attr.value {
            case ast.Static_Value:
                fmt.sbprintf(b, "    %s = \"%s\",\n", attr.name, v.value)
            case ast.Dynamic_Value:
                expr := resolve_expr(g, v.expr)
                fmt.sbprintf(b, "    %s = %s,\n", attr.name, expr)
            case ast.Bool_Shorthand:
                fmt.sbprintf(b, "    %s = true,\n", attr.name)
            }
        }
        for sd in snippet_defs {
            render_name := fmt.tprintf("_%s_%s_%d_%s_render", pkg, comp_lower, idx, sd.name)
            param_type := ""
            if pt, ok := sd.param_type.?; ok {
                param_type = pt
            }
            g.need_rt = true
            write_indent(g, b)
            if len(param_type) > 0 {
                fmt.sbprintf(b, "    %s = rt.Snippet(%s){{\n", sd.name, param_type)
            } else {
                fmt.sbprintf(b, "    %s = rt.Children{{\n", sd.name)
            }
            write_indent(g, b)
            fmt.sbprintf(b, "        func = %s,\n", render_name)
            write_indent(g, b)
            strings.write_string(b, "        ctx = nil,\n")
            write_indent(g, b)
            strings.write_string(b, "    },\n")
        }
        write_indent(g, b)
        strings.write_string(b, "})\n")
    } else {
        // Self-closing or no children
        write_indent(g, b)
        if len(pkg) > 0 {
            fmt.sbprintf(b, "%s.render(w, %s.Props{{\n", pkg, pkg)
        } else {
            fmt.sbprintf(b, "render(w, Props{{\n")
        }
        for attr in comp.attributes {
            write_indent(g, b)
            switch v in attr.value {
            case ast.Static_Value:
                fmt.sbprintf(b, "    %s = \"%s\",\n", attr.name, v.value)
            case ast.Dynamic_Value:
                expr := resolve_expr(g, v.expr)
                fmt.sbprintf(b, "    %s = %s,\n", attr.name, expr)
            case ast.Bool_Shorthand:
                fmt.sbprintf(b, "    %s = true,\n", attr.name)
            }
        }
        write_indent(g, b)
        strings.write_string(b, "})\n")
    }
    _ = has_children
}

// gen_nodes_with_ctx generates nodes but uses ctx.xxx for outer variable references
gen_nodes_with_ctx :: proc(g: ^Generator, nodes: []ast.Node, b: ^strings.Builder, refs: []string, ctx_name: string) {
    // Temporarily remap props fields that appear in refs to ctx.xxx
    // We do this by modifying the scope: refs are already in scope (added by caller)
    // But we need them to resolve to ctx.xxx not bare name
    // Actually the caller did push_scope and add_to_scope for refs
    // So resolve_expr will return bare name (not props.xxx)
    // We need them to be ctx.xxx
    // Approach: intercept at gen_expression level

    // Save old props_fields
    old_fields := g.props_fields

    // Create a fake scope where refs map to ctx.field form
    // We'll do this differently: remove refs from props_fields temporarily
    // and add them to scope, then post-process to replace bare name with ctx.xxx

    // Actually the cleanest approach: generate into a temp buffer,
    // then replace bare refs with ctx.xxx

    tmp := strings.Builder{}
    strings.builder_init(&tmp)
    gen_nodes(g, nodes, &tmp)
    result := strings.to_string(tmp)

    // Replace "props.ref" with "ctx.ref" for each ref
    final := result
    for ref in refs {
        from := fmt.tprintf("props.%s", ref)
        to := fmt.tprintf("ctx.%s", ref)
        new_result, _ := strings.replace_all(final, from, to)
        final = new_result
    }

    strings.write_string(b, final)
    g.props_fields = old_fields
}

// collect_var_refs collects all top-level variable references in nodes
// that are props fields (not local scope vars)
collect_var_refs :: proc(g: ^Generator, nodes: []ast.Node) -> []string {
    seen := make(map[string]bool)
    refs_dyn := make([dynamic]string)
    collect_refs_recursive(g, nodes, &seen, &refs_dyn)
    return refs_dyn[:]
}

collect_refs_recursive :: proc(g: ^Generator, nodes: []ast.Node, seen: ^map[string]bool, refs: ^[dynamic]string) {
    for node in nodes {
        switch n in node {
        case ast.Text:
            // no refs
        case ast.Element:
            for attr in n.attributes {
                switch v in attr.value {
                case ast.Dynamic_Value:
                    root := get_root_name(v.expr)
                    if !is_in_scope(g, root) && len(root) > 0 {
                        if !seen[root] {
                            seen[root] = true
                            append(refs, root)
                        }
                    }
                case ast.Static_Value, ast.Bool_Shorthand:
                    // nothing
                }
            }
            collect_refs_recursive(g, n.children[:], seen, refs)
        case ast.Expression:
            root := get_root_name(n.content)
            if !is_in_scope(g, root) && len(root) > 0 {
                if !seen[root] {
                    seen[root] = true
                    append(refs, root)
                }
            }
        case ast.Raw_Html:
            root := get_root_name(n.content)
            if !is_in_scope(g, root) && len(root) > 0 {
                if !seen[root] {
                    seen[root] = true
                    append(refs, root)
                }
            }
        case ast.If_Block:
            root := get_root_name(n.condition)
            if !is_in_scope(g, root) && len(root) > 0 {
                if !seen[root] {
                    seen[root] = true
                    append(refs, root)
                }
            }
            collect_refs_recursive(g, n.children[:], seen, refs)
            if eb, ok := n.else_body.?; ok {
                collect_refs_recursive(g, eb[:], seen, refs)
            }
        case ast.Each_Block:
            root := get_root_name(n.iterable)
            if !is_in_scope(g, root) && len(root) > 0 {
                if !seen[root] {
                    seen[root] = true
                    append(refs, root)
                }
            }
            collect_refs_recursive(g, n.children[:], seen, refs)
        case ast.Snippet_Def:
            collect_refs_recursive(g, n.children[:], seen, refs)
        case ast.Render_Call:
            // nothing direct
        case ast.Component:
            collect_refs_recursive(g, n.children[:], seen, refs)
        }
    }
}

get_root_name :: proc(expr: string) -> string {
    trimmed := strings.trim_space(expr)
    dot_idx := strings.index(trimmed, ".")
    if dot_idx >= 0 {
        return strings.trim_space(trimmed[:dot_idx])
    }
    return trimmed
}

// ─── layout inlining ──────────────────────────────────────────────────────────

// gen_layout_inlined generates code that inlines the layout chain around the
// page content. layout_chain is ordered outermost to innermost.
//
// Strategy: generate innermost content first into a string buffer, then wrap it
// in each successive layout by setting g.layout_children_content so that
// gen_render_call substitutes {@render children()} with the inner content.
//
// The result is equivalent to:
//   layout[0] wraps (layout[1] wraps (... wraps page_content))
gen_layout_inlined :: proc(g: ^Generator, page_nodes: []ast.Node, layout_chain: []ast.Document, b: ^strings.Builder) {
    if len(layout_chain) == 0 {
        gen_nodes(g, page_nodes, b)
        return
    }

    // Step 1: Generate page content into a temp buffer
    page_buf := strings.Builder{}
    strings.builder_init(&page_buf)
    gen_nodes(g, page_nodes, &page_buf)
    inner_content := strings.to_string(page_buf)

    // Step 2: Wrap with each layout from innermost to outermost
    // We iterate the chain in reverse so that we progressively wrap inner content
    for i := len(layout_chain) - 1; i >= 0; i -= 1 {
        layout := layout_chain[i]

        // Save previous children content state
        old_children := g.layout_children_content

        // Set the current inner content as what {@render children()} will emit
        g.layout_children_content = inner_content

        // Generate this layout into a temp buffer
        layout_buf := strings.Builder{}
        strings.builder_init(&layout_buf)
        gen_nodes(g, layout.children[:], &layout_buf)
        inner_content = strings.to_string(layout_buf)

        // Restore previous state
        g.layout_children_content = old_children
    }

    // Step 3: Write the final wrapped content
    strings.write_string(b, inner_content)
}
