// src/codegen/codegen.odin
package codegen

import "core:strings"
import "core:fmt"
import "../ast"

// ─── state ────────────────────────────────────────────────────────────────────

Generator :: struct {
    b:               strings.Builder,
    // imports
    need_fmt:        bool,
    need_rt:    bool,
    // scope stack: each entry is a set of local variable names
    scopes:          [dynamic]map[string]bool,
    // counters for unique child/snippet proc names
    child_counter:   int,
    // top-level procs/structs that need to be emitted before render
    preamble:        strings.Builder,
    // props lookup for type resolution
    props_fields:    map[string]string, // name -> type_expr
    // snippet fields (name -> arg_type or "")
    snippet_fields:  map[string]string,
    // indentation level
    indent:          int,
    // When non-nil, {@render children()} emits this pre-generated content instead
    // of the normal rt.children_render call. Used for layout inlining.
    layout_children_content: Maybe(string),
    // When true, whitespace in Text nodes is preserved exactly (inside <pre>/<code>)
    preserve_whitespace: bool,
    // Prefix for props references ("props" in render body, "ctx" in component children)
    props_prefix: string,
}

// ─── entry points ─────────────────────────────────────────────────────────────

generate :: proc(doc: ast.Document, pkg_name: string, rt_import: string = "rt") -> string {
    return generate_page(doc, pkg_name, nil, nil, rt_import)
}

generate_page :: proc(doc: ast.Document, pkg_name: string, layout_chain: []ast.Document, route_params: []string = nil, rt_import: string = "rt") -> string {
    g := Generator{}
    strings.builder_init(&g.b)
    strings.builder_init(&g.preamble)
    g.scopes = make([dynamic]map[string]bool)
    g.props_fields = make(map[string]string)
    g.snippet_fields = make(map[string]string)
    g.props_prefix = "props"

    // Build props_fields and snippet_fields lookup
    if script, ok := doc.script.?; ok {
        if props_def, ok2 := script.props.?; ok2 {
            for field in props_def.fields {
                g.props_fields[field.name] = field.type_expr
                if field.is_snippet {
                    if arg_type, ok3 := field.snippet_arg_type.?; ok3 {
                        g.snippet_fields[field.name] = arg_type
                    } else {
                        g.snippet_fields[field.name] = ""
                    }
                }
            }
        }
    }

    // Scan children for component usages - we need preamble for snippet call sites
    // (this is a two-pass approach: first collect preamble, then emit body)
    // We'll do it inline and collect preamble separately

    // Generate body first into a temp builder, then assemble
    body_b := strings.Builder{}
    strings.builder_init(&body_b)

    // generate render body
    has_props := false
    if script, ok := doc.script.?; ok {
        if _, ok2 := script.props.?; ok2 {
            has_props = true
        }
    }

    // Push global scope — add route params so they resolve bare (not props.)
    push_scope(&g)
    if route_params != nil {
        for rp in route_params {
            add_to_scope(&g, rp)
        }
    }

    // Generate nodes into body
    g.indent = 1

    // If we have a layout chain, inline layouts around the page content.
    // layout_chain is ordered outermost to innermost.
    // We emit: layout[0].before + layout[1].before + ... + page + ... + layout[1].after + layout[0].after
    if layout_chain != nil && len(layout_chain) > 0 {
        gen_layout_inlined(&g, doc.children[:], layout_chain, &g.b)
    } else {
        gen_nodes(&g, doc.children[:], &g.b)
    }

    pop_scope(&g)

    // Now assemble the full file
    out := strings.Builder{}
    strings.builder_init(&out)

    // Header
    strings.write_string(&out, "// Code generated by ohtml. DO NOT EDIT.\n")
    fmt.sbprintf(&out, "package %s\n\n", pkg_name)

    // Imports
    strings.write_string(&out, `import "core:io"`)
    strings.write_string(&out, "\n")
    if g.need_fmt {
        strings.write_string(&out, `import "core:fmt"`)
        strings.write_string(&out, "\n")
    }
    if g.need_rt {
        fmt.sbprintf(&out, "import \"%s\"", rt_import)
        strings.write_string(&out, "\n")
    }

    // User imports from script block (skip codegen-managed ones)
    if script, ok := doc.script.?; ok {
        for imp in script.imports {
            if imp.path == "core:io" || imp.path == "core:fmt" {
                continue
            }
            if alias, ok2 := imp.alias.?; ok2 {
                fmt.sbprintf(&out, "import %s \"%s\"\n", alias, imp.path)
            } else {
                fmt.sbprintf(&out, "import \"%s\"\n", imp.path)
            }
        }
    }

    strings.write_string(&out, "\n")

    // Extra type definitions from script (e.g. custom structs used by Props)
    if script, ok := doc.script.?; ok {
        extra := extract_extra_defs(script.raw)
        if len(extra) > 0 {
            strings.write_string(&out, extra)
            strings.write_string(&out, "\n\n")
        }
    }

    // Props struct (rewritten with runtime types)
    if script, ok := doc.script.?; ok {
        if props_def, ok2 := script.props.?; ok2 {
            strings.write_string(&out, "Props :: struct {\n")
            for field in props_def.fields {
                if field.is_snippet {
                    if arg_type, ok3 := field.snippet_arg_type.?; ok3 {
                        fmt.sbprintf(&out, "    %s: rt.Snippet(%s),\n", field.name, arg_type)
                    } else {
                        fmt.sbprintf(&out, "    %s: rt.Children,\n", field.name)
                    }
                } else {
                    fmt.sbprintf(&out, "    %s: %s,\n", field.name, field.type_expr)
                }
            }
            strings.write_string(&out, "}\n\n")
        }
    }

    // Preamble (helper structs/procs for component children)
    preamble_str := strings.to_string(g.preamble)
    if len(preamble_str) > 0 {
        strings.write_string(&out, preamble_str)
        strings.write_string(&out, "\n")
    }

    // render proc signature
    strings.write_string(&out, "render :: proc(w: io.Writer")
    if route_params != nil {
        for rp in route_params {
            fmt.sbprintf(&out, ", %s: string", rp)
        }
    }
    if has_props {
        strings.write_string(&out, ", props: Props")
    }
    strings.write_string(&out, ") {\n")

    // Body
    strings.write_string(&out, strings.to_string(g.b))

    strings.write_string(&out, "}\n")

    return merge_static_writes(strings.to_string(out))
}

// ─── scope helpers ────────────────────────────────────────────────────────────

push_scope :: proc(g: ^Generator) {
    scope := make(map[string]bool)
    append(&g.scopes, scope)
}

pop_scope :: proc(g: ^Generator) {
    if len(g.scopes) > 0 {
        scope := g.scopes[len(g.scopes)-1]
        delete(scope)
        resize(&g.scopes, len(g.scopes)-1)
    }
}

add_to_scope :: proc(g: ^Generator, name: string) {
    if len(g.scopes) > 0 {
        g.scopes[len(g.scopes)-1][name] = true
    }
}

is_in_scope :: proc(g: ^Generator, name: string) -> bool {
    // Walk from top of stack downward
    for i := len(g.scopes) - 1; i >= 0; i -= 1 {
        if g.scopes[i][name] {
            return true
        }
    }
    return false
}

// ─── indent helpers ───────────────────────────────────────────────────────────

write_indent :: proc(g: ^Generator, b: ^strings.Builder) {
    for i := 0; i < g.indent; i += 1 {
        strings.write_string(b, "    ")
    }
}

// ─── identifier helpers ──────────────────────────────────────────────────────

is_ident_start :: proc(c: u8) -> bool {
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'
}

is_ident_char :: proc(c: u8) -> bool {
    return is_ident_start(c) || (c >= '0' && c <= '9')
}

is_odin_keyword :: proc(ident: string) -> bool {
    switch ident {
    case "true", "false", "nil":
        return true
    }
    return false
}

// ─── resolve expression name ──────────────────────────────────────────────────

// Walk an expression string, find identifiers, and prefix props references
// with g.props_prefix (normally "props", or "ctx" in component children).
// Handles literals, unary operators, compound expressions, and function calls.
resolve_expr :: proc(g: ^Generator, expr: string) -> string {
    trimmed := strings.trim_space(expr)
    if len(trimmed) == 0 { return trimmed }

    result := strings.Builder{}
    strings.builder_init(&result)

    i := 0
    for i < len(trimmed) {
        c := trimmed[i]

        // Skip string literals
        if c == '"' {
            start := i
            i += 1
            for i < len(trimmed) {
                if trimmed[i] == '\\' {
                    i += 1
                } else if trimmed[i] == '"' {
                    break
                }
                i += 1
            }
            if i < len(trimmed) { i += 1 } // closing quote
            strings.write_string(&result, trimmed[start:i])
            continue
        }

        // Numeric literals
        if c >= '0' && c <= '9' {
            start := i
            for i < len(trimmed) && ((trimmed[i] >= '0' && trimmed[i] <= '9') || trimmed[i] == '.' || trimmed[i] == '_') {
                i += 1
            }
            strings.write_string(&result, trimmed[start:i])
            continue
        }

        // Identifiers (possibly dotted: fmt.tprintf, item.name)
        if is_ident_start(c) {
            start := i
            for i < len(trimmed) && is_ident_char(trimmed[i]) {
                i += 1
            }
            // Include dotted segments (foo.bar.baz)
            for i < len(trimmed) && trimmed[i] == '.' && (i + 1) < len(trimmed) && is_ident_start(trimmed[i + 1]) {
                i += 1 // skip dot
                for i < len(trimmed) && is_ident_char(trimmed[i]) {
                    i += 1
                }
            }
            ident := trimmed[start:i]

            // Check if followed by '(' — function/proc call, don't prefix
            peek := i
            for peek < len(trimmed) && (trimmed[peek] == ' ' || trimmed[peek] == '\t') {
                peek += 1
            }
            if peek < len(trimmed) && trimmed[peek] == '(' {
                strings.write_string(&result, ident)
            } else {
                strings.write_string(&result, resolve_ident(g, ident))
            }
            continue
        }

        // Everything else: operators, parens, brackets, whitespace
        strings.write_byte(&result, c)
        i += 1
    }

    return strings.to_string(result)
}

// Resolve a single identifier (possibly dotted like item.name).
// Keywords pass through; scope locals pass through; props fields get prefixed.
resolve_ident :: proc(g: ^Generator, ident: string) -> string {
    if is_odin_keyword(ident) { return ident }

    dot_idx := strings.index(ident, ".")
    root := ident
    if dot_idx >= 0 { root = ident[:dot_idx] }

    if is_in_scope(g, root) { return ident }

    if root in g.props_fields {
        return strings.concatenate({g.props_prefix, ".", ident})
    }

    // Unknown — leave as-is (package name, import, etc.)
    return ident
}

// Get the type of a props field. Returns "" if not found.
props_field_type :: proc(g: ^Generator, name: string) -> string {
    if t, ok := g.props_fields[name]; ok {
        return t
    }
    return ""
}

// Determine the effective type of an expression for rendering decisions.
// Used by attribute codegen to choose bool/string/other rendering paths.
expr_field_type :: proc(g: ^Generator, expr: string) -> string {
    trimmed := strings.trim_space(expr)
    if len(trimmed) == 0 { return "" }

    // Unary negation → bool
    if trimmed[0] == '!' { return "bool" }

    // Literal booleans
    if trimmed == "true" || trimmed == "false" { return "bool" }

    // Literal number
    if trimmed[0] >= '0' && trimmed[0] <= '9' { return "" }

    // fmt.* function calls return strings
    if strings.has_prefix(trimmed, "fmt.") { return "string" }

    // Simple identifier or field access — look up root in props_fields
    root := trimmed
    dot_idx := strings.index(trimmed, ".")
    if dot_idx >= 0 { root = trimmed[:dot_idx] }

    if is_in_scope(g, root) { return "" }

    return props_field_type(g, root)
}

// ─── HTML string collapsing ───────────────────────────────────────────────────

// flush_static emits a pending static buffer as an io.write_string call
flush_static :: proc(g: ^Generator, buf: ^strings.Builder, b: ^strings.Builder) {
    s := strings.to_string(buf^)
    if len(s) > 0 {
        write_indent(g, b)
        fmt.sbprintf(b, "io.write_string(w, %q)\n", s)
        strings.builder_reset(buf)
    }
}

// merge_static_writes post-processes generated code to merge consecutive
// io.write_string(w, "...") lines into a single call, reducing function call
// overhead at runtime. Lines must share the same indentation to be merged.
merge_static_writes :: proc(code: string) -> string {
    MARKER :: `io.write_string(w, "`

    lines := strings.split(code, "\n")
    defer delete(lines)

    result := strings.Builder{}
    strings.builder_init(&result)

    i := 0
    for i < len(lines) {
        trimmed := strings.trim_left_space(lines[i])
        if !strings.has_prefix(trimmed, MARKER) || !strings.has_suffix(trimmed, `")`) {
            strings.write_string(&result, lines[i])
            strings.write_byte(&result, '\n')
            i += 1
            continue
        }

        // Compute indent (leading whitespace)
        indent := lines[i][:len(lines[i]) - len(trimmed)]

        // Extract string content from first line
        merged := strings.Builder{}
        strings.builder_init(&merged)
        // Content is between MARKER and closing ")
        content := trimmed[len(MARKER):len(trimmed) - 2]
        strings.write_string(&merged, content)
        i += 1

        // Merge subsequent lines with same indent and pattern
        for i < len(lines) {
            next_trimmed := strings.trim_left_space(lines[i])
            next_indent := lines[i][:len(lines[i]) - len(next_trimmed)]
            if next_indent != indent { break }
            if !strings.has_prefix(next_trimmed, MARKER) { break }
            if !strings.has_suffix(next_trimmed, `")`) { break }
            next_content := next_trimmed[len(MARKER):len(next_trimmed) - 2]
            strings.write_string(&merged, next_content)
            i += 1
        }

        // Emit merged line
        strings.write_string(&result, indent)
        strings.write_string(&result, MARKER)
        strings.write_string(&result, strings.to_string(merged))
        strings.write_string(&result, "\")\n")
    }

    // Remove trailing extra newline if present (split adds one)
    out := strings.to_string(result)
    if len(out) > 0 && out[len(out)-1] == '\n' {
        // The original code may or may not end with newline; trim one extra
        // that split+rejoin adds. Check if original ends with \n.
        if len(code) > 0 && code[len(code)-1] != '\n' {
            return out[:len(out)-1]
        }
    }
    return out
}

// Generates a list of nodes, collapsing adjacent static text into single io.write_string calls
gen_nodes :: proc(g: ^Generator, nodes: []ast.Node, b: ^strings.Builder) {
    static_buf := strings.Builder{}
    strings.builder_init(&static_buf)

    for node in nodes {
        switch n in node {
        case ast.Text:
            if !g.preserve_whitespace && strings.trim_space(n.content) == "" {
                // Pure-whitespace inter-element text: collapse to nothing
                // (omit to avoid emitting raw newlines/spaces between tags)
            } else {
                strings.write_string(&static_buf, n.content)
            }
        case ast.Element:
            // Check if the entire element (attrs + children) is static BEFORE writing anything
            if are_element_static(n) {
                // Fully static: accumulate into static_buf
                gen_element_static_open(&static_buf, n)
                if !n.self_close {
                    // Preserve whitespace inside <pre> and <code>
                    child_preserve := g.preserve_whitespace || n.tag == "pre" || n.tag == "code"
                    gen_nodes_static(&static_buf, n.children[:], child_preserve)
                    gen_element_close(&static_buf, n.tag)
                }
            } else {
                // Has dynamic attrs or dynamic children: flush static so far, go dynamic
                flush_static(g, &static_buf, b)
                gen_element_open_dynamic(g, n, b)
                if !n.self_close {
                    // Preserve whitespace inside <pre> and <code>
                    old_preserve := g.preserve_whitespace
                    if n.tag == "pre" || n.tag == "code" {
                        g.preserve_whitespace = true
                    }
                    gen_nodes(g, n.children[:], b)
                    g.preserve_whitespace = old_preserve
                    // Close tag goes into static_buf for potential collapsing
                    gen_element_close(&static_buf, n.tag)
                }
            }
        case ast.Expression:
            flush_static(g, &static_buf, b)
            gen_expression(g, n, b)
        case ast.Raw_Html:
            flush_static(g, &static_buf, b)
            gen_raw_html(g, n, b)
        case ast.If_Block:
            flush_static(g, &static_buf, b)
            gen_if_block(g, n, b)
        case ast.Each_Block:
            flush_static(g, &static_buf, b)
            gen_each_block(g, n, b)
        case ast.Snippet_Def:
            flush_static(g, &static_buf, b)
            gen_snippet_def(g, n, b)
        case ast.Render_Call:
            flush_static(g, &static_buf, b)
            gen_render_call(g, n, b)
        case ast.Component:
            flush_static(g, &static_buf, b)
            gen_component(g, n, b)
        }
    }
    flush_static(g, &static_buf, b)
}

// gen_node generates a single node
gen_node :: proc(g: ^Generator, node: ast.Node, b: ^strings.Builder) {
    nodes := [1]ast.Node{node}
    gen_nodes(g, nodes[:], b)
}

// Check if all nodes are purely static (no expressions, control flow, etc.)
are_all_static :: proc(nodes: []ast.Node) -> bool {
    for node in nodes {
        switch n in node {
        case ast.Text:
            // static
        case ast.Element:
            if !are_element_static(n) { return false }
        case ast.Raw_Html:
            // Literal Raw_Html (e.g. DOCTYPE) is static; expression Raw_Html is not
            if !n.is_literal { return false }
        case ast.Expression, ast.If_Block, ast.Each_Block,
             ast.Snippet_Def, ast.Render_Call, ast.Component:
            return false
        }
    }
    return true
}

are_element_static :: proc(el: ast.Element) -> bool {
    // Check attrs for dynamic
    for attr in el.attributes {
        switch _ in attr.value {
        case ast.Static_Value:
            // ok
        case ast.Dynamic_Value, ast.Bool_Shorthand:
            return false
        }
    }
    return are_all_static(el.children[:])
}

// ─── static element generation ────────────────────────────────────────────────

// Write element opening tag to a static buffer (no dynamic checks)
gen_element_static_open :: proc(buf: ^strings.Builder, el: ast.Element) {
    fmt.sbprintf(buf, "<%s", el.tag)
    for attr in el.attributes {
        switch v in attr.value {
        case ast.Static_Value:
            fmt.sbprintf(buf, " %s=\"%s\"", attr.name, v.value)
        case ast.Dynamic_Value:
            // Shouldn't be called for static elements
        case ast.Bool_Shorthand:
            // Shouldn't be called for static elements
        }
    }
    if el.self_close {
        strings.write_string(buf, "/>")
    } else {
        strings.write_string(buf, ">")
    }
}

gen_element_close :: proc(buf: ^strings.Builder, tag: string) {
    fmt.sbprintf(buf, "</%s>", tag)
}

// Write static content of nodes into a static buffer.
// preserve_ws: when true, write text exactly; when false, collapse pure-whitespace text.
gen_nodes_static :: proc(buf: ^strings.Builder, nodes: []ast.Node, preserve_ws: bool = false) {
    for node in nodes {
        switch n in node {
        case ast.Text:
            if !preserve_ws && strings.trim_space(n.content) == "" {
                // Collapse pure-whitespace inter-element text
            } else {
                strings.write_string(buf, n.content)
            }
        case ast.Element:
            gen_element_static_open(buf, n)
            if !n.self_close {
                child_preserve := preserve_ws || n.tag == "pre" || n.tag == "code"
                gen_nodes_static(buf, n.children[:], child_preserve)
                gen_element_close(buf, n.tag)
            }
        case ast.Raw_Html:
            // Literal Raw_Html nodes (e.g. DOCTYPE) can appear in static contexts
            if n.is_literal {
                strings.write_string(buf, n.content)
            }
            // Non-literal (expression) Raw_Html should not appear in static context
        case ast.Expression, ast.If_Block, ast.Each_Block,
             ast.Snippet_Def, ast.Render_Call, ast.Component:
            // Should not happen in static context
        }
    }
}

// ─── dynamic element generation ───────────────────────────────────────────────

// Emit dynamic open tag (already flushed static, so write directly to b)
gen_element_open_dynamic :: proc(g: ^Generator, el: ast.Element, b: ^strings.Builder) {
    // Collect static prefix of the open tag
    static_prefix := strings.Builder{}
    strings.builder_init(&static_prefix)
    fmt.sbprintf(&static_prefix, "<%s", el.tag)

    for attr in el.attributes {
        switch v in attr.value {
        case ast.Static_Value:
            fmt.sbprintf(&static_prefix, " %s=\"%s\"", attr.name, v.value)
        case ast.Dynamic_Value:
            dv_field_type := expr_field_type(g, v.expr)
            dv_expr := resolve_expr(g, v.expr)

            if dv_field_type == "bool" {
                // Bool attribute: flush prefix, emit if block (no "name=")
                prefix := strings.to_string(static_prefix)
                if len(prefix) > 0 {
                    write_indent(g, b)
                    fmt.sbprintf(b, "io.write_string(w, %q)\n", prefix)
                    strings.builder_reset(&static_prefix)
                }
                write_indent(g, b)
                fmt.sbprintf(b, "if %s {{\n", dv_expr)
                g.indent += 1
                write_indent(g, b)
                fmt.sbprintf(b, "io.write_string(w, \" %s\")\n", attr.name)
                g.indent -= 1
                write_indent(g, b)
                strings.write_string(b, "}\n")
            } else {
                // Regular dynamic attribute: flush prefix, emit name=, value, closing quote
                prefix := strings.to_string(static_prefix)
                if len(prefix) > 0 {
                    write_indent(g, b)
                    fmt.sbprintf(b, "io.write_string(w, %q)\n", prefix)
                    strings.builder_reset(&static_prefix)
                }
                write_indent(g, b)
                fmt.sbprintf(b, "io.write_string(w, %q)\n", fmt.tprintf(" %s=\"", attr.name))
                g.need_rt = true
                if dv_field_type == "string" {
                    write_indent(g, b)
                    fmt.sbprintf(b, "rt.html_escape(w, %s)\n", dv_expr)
                } else {
                    g.need_fmt = true
                    write_indent(g, b)
                    fmt.sbprintf(b, "rt.html_escape(w, fmt.tprint(%s))\n", dv_expr)
                }
                write_indent(g, b)
                strings.write_string(b, "io.write_string(w, \"\\\"\")\n")
            }
        case ast.Bool_Shorthand:
            // Flush static prefix
            prefix := strings.to_string(static_prefix)
            if len(prefix) > 0 {
                write_indent(g, b)
                fmt.sbprintf(b, "io.write_string(w, %q)\n", prefix)
                strings.builder_reset(&static_prefix)
            }
            // Boolean attribute: if props.disabled { io.write_string(w, " disabled") }
            expr := resolve_expr(g, attr.name)
            write_indent(g, b)
            fmt.sbprintf(b, "if %s {{\n", expr)
            g.indent += 1
            write_indent(g, b)
            fmt.sbprintf(b, "io.write_string(w, \" %s\")\n", attr.name)
            g.indent -= 1
            write_indent(g, b)
            strings.write_string(b, "}\n")
        }
    }

    // Flush remaining static prefix + ">"
    if el.self_close {
        strings.write_string(&static_prefix, "/>")
    } else {
        strings.write_string(&static_prefix, ">")
    }
    prefix := strings.to_string(static_prefix)
    if len(prefix) > 0 {
        write_indent(g, b)
        fmt.sbprintf(b, "io.write_string(w, %q)\n", prefix)
    }
}

// ─── expression ───────────────────────────────────────────────────────────────

gen_expression :: proc(g: ^Generator, expr: ast.Expression, b: ^strings.Builder) {
    content := strings.trim_space(expr.content)
    resolved := resolve_expr(g, content)
    g.need_rt = true

    field_type := expr_field_type(g, content)

    if field_type == "string" {
        write_indent(g, b)
        fmt.sbprintf(b, "rt.html_escape(w, %s)\n", resolved)
    } else {
        // Non-string: use fmt.tprint
        g.need_fmt = true
        write_indent(g, b)
        fmt.sbprintf(b, "rt.html_escape(w, fmt.tprint(%s))\n", resolved)
    }
}

// ─── raw html ─────────────────────────────────────────────────────────────────

gen_raw_html :: proc(g: ^Generator, raw: ast.Raw_Html, b: ^strings.Builder) {
    content := strings.trim_space(raw.content)
    write_indent(g, b)
    if raw.is_literal {
        // Literal HTML content (e.g. <!DOCTYPE html>) — emit as a quoted string literal
        fmt.sbprintf(b, "io.write_string(w, %q)\n", content)
    } else {
        // Expression variable (e.g. {@html my_var}) — resolve and emit as identifier
        resolved := resolve_expr(g, content)
        fmt.sbprintf(b, "io.write_string(w, %s)\n", resolved)
    }
}

// ─── if block ─────────────────────────────────────────────────────────────────

gen_if_block :: proc(g: ^Generator, ib: ast.If_Block, b: ^strings.Builder) {
    condition := resolve_expr(g, ib.condition)
    write_indent(g, b)
    fmt.sbprintf(b, "if %s {{\n", condition)
    g.indent += 1
    push_scope(g)
    gen_nodes(g, ib.children[:], b)
    pop_scope(g)
    g.indent -= 1

    for else_if in ib.else_ifs {
        write_indent(g, b)
        ei_cond := resolve_expr(g, else_if.condition)
        fmt.sbprintf(b, "}} else if %s {{\n", ei_cond)
        g.indent += 1
        push_scope(g)
        gen_nodes(g, else_if.children[:], b)
        pop_scope(g)
        g.indent -= 1
    }

    if else_body, ok := ib.else_body.?; ok {
        write_indent(g, b)
        strings.write_string(b, "} else {\n")
        g.indent += 1
        push_scope(g)
        gen_nodes(g, else_body[:], b)
        pop_scope(g)
        g.indent -= 1
    }

    write_indent(g, b)
    strings.write_string(b, "}\n")
}

// ─── each block ───────────────────────────────────────────────────────────────

gen_each_block :: proc(g: ^Generator, eb: ast.Each_Block, b: ^strings.Builder) {
    iterable := resolve_expr(g, eb.iterable)

    if else_body, ok := eb.else_body.?; ok {
        // Wrap with len check
        write_indent(g, b)
        fmt.sbprintf(b, "if len(%s) > 0 {{\n", iterable)
        g.indent += 1
        gen_each_loop(g, eb, iterable, b)
        g.indent -= 1
        write_indent(g, b)
        strings.write_string(b, "} else {\n")
        g.indent += 1
        push_scope(g)
        gen_nodes(g, else_body[:], b)
        pop_scope(g)
        g.indent -= 1
        write_indent(g, b)
        strings.write_string(b, "}\n")
    } else {
        gen_each_loop(g, eb, iterable, b)
    }
}

gen_each_loop :: proc(g: ^Generator, eb: ast.Each_Block, iterable: string, b: ^strings.Builder) {
    if index, ok := eb.index.?; ok {
        write_indent(g, b)
        // Odin: for value, index in collection
        fmt.sbprintf(b, "for %s, %s in %s {{\n", eb.binding, index, iterable)
    } else {
        write_indent(g, b)
        fmt.sbprintf(b, "for %s in %s {{\n", eb.binding, iterable)
    }
    g.indent += 1
    push_scope(g)
    add_to_scope(g, eb.binding)
    if index, ok := eb.index.?; ok {
        add_to_scope(g, index)
    }
    gen_nodes(g, eb.children[:], b)
    pop_scope(g)
    g.indent -= 1
    write_indent(g, b)
    strings.write_string(b, "}\n")
}

// ─── snippet def ──────────────────────────────────────────────────────────────

gen_snippet_def :: proc(g: ^Generator, sd: ast.Snippet_Def, b: ^strings.Builder) {
    // Inline snippet definition - generate a proc for it
    // This is used when a Component contains {#snippet row(item: Item)}...{/snippet}
    // We generate it into preamble
    idx := g.child_counter
    g.child_counter += 1

    param_name := ""
    param_type := ""
    if pn, ok := sd.param_name.?; ok {
        param_name = pn
    }
    if pt, ok := sd.param_type.?; ok {
        param_type = pt
    }

    proc_name := fmt.tprintf("_%s_%s_%d_render", sd.name, sd.name, idx)

    // Generate the snippet render proc into preamble
    if len(param_type) > 0 {
        fmt.sbprintf(&g.preamble, "%s :: proc(w: io.Writer, ctx_ptr: rawptr, %s: %s) {{\n", proc_name, param_name, param_type)
    } else {
        fmt.sbprintf(&g.preamble, "%s :: proc(w: io.Writer, ctx_ptr: rawptr) {{\n", proc_name)
    }
    g.indent = 1

    old_b := g.b
    g.b = strings.Builder{}
    strings.builder_init(&g.b)

    push_scope(g)
    if len(param_name) > 0 {
        add_to_scope(g, param_name)
    }
    gen_nodes(g, sd.children[:], &g.b)
    pop_scope(g)

    strings.write_string(&g.preamble, strings.to_string(g.b))
    g.b = old_b

    strings.write_string(&g.preamble, "}\n\n")
    g.indent = 1

    // Emit the snippet binding in place (inline in render body)
    _ = idx
}

// ─── render call ──────────────────────────────────────────────────────────────

gen_render_call :: proc(g: ^Generator, rc: ast.Render_Call, b: ^strings.Builder) {
    name := rc.name

    // Layout inlining: if this is a {@render children()} and we have injected content, emit it directly.
    if name == "children" {
        if content, ok := g.layout_children_content.?; ok {
            strings.write_string(b, content)
            return
        }
    }

    g.need_rt = true

    // Check if it's a children call (no args or explicit children())
    if snippet_arg_type, ok := g.snippet_fields[name]; ok {
        if len(snippet_arg_type) == 0 {
            // children: rt.Children
            write_indent(g, b)
            fmt.sbprintf(b, "rt.children_render(w, props.%s)\n", name)
        } else {
            // typed snippet
            if args_val, ok2 := rc.args.?; ok2 {
                arg := resolve_expr(g, strings.trim_space(args_val))
                write_indent(g, b)
                fmt.sbprintf(b, "rt.snippet_render(%s, w, props.%s, %s)\n", snippet_arg_type, name, arg)
            } else {
                write_indent(g, b)
                fmt.sbprintf(b, "rt.snippet_render(%s, w, props.%s)\n", snippet_arg_type, name)
            }
        }
    } else {
        // Not a known snippet field — could be a local snippet var
        if args_val, ok := rc.args.?; ok {
            arg := resolve_expr(g, strings.trim_space(args_val))
            write_indent(g, b)
            fmt.sbprintf(b, "rt.snippet_render(_, w, %s, %s)\n", name, arg)
        } else {
            write_indent(g, b)
            fmt.sbprintf(b, "rt.children_render(w, %s)\n", name)
        }
    }
}

// ─── component ────────────────────────────────────────────────────────────────

gen_component :: proc(g: ^Generator, comp: ast.Component, b: ^strings.Builder) {
    idx := g.child_counter
    g.child_counter += 1

    pkg := strings.to_lower(comp.pkg)
    comp_lower := strings.to_lower(comp.name)

    // Separate snippet defs from non-snippet children, filtering whitespace text
    snippet_defs: [dynamic]ast.Snippet_Def
    non_snippet_children: [dynamic]ast.Node

    for child in comp.children {
        if sd, ok := child.(ast.Snippet_Def); ok {
            append(&snippet_defs, sd)
        } else if text, ok := child.(ast.Text); ok {
            if strings.trim_space(text.content) != "" {
                append(&non_snippet_children, child)
            }
        } else {
            append(&non_snippet_children, child)
        }
    }

    has_non_snippet := len(non_snippet_children) > 0
    has_snippet_defs := len(snippet_defs) > 0

    if has_non_snippet {
        ctx_name := fmt.tprintf("_%s_%s_%d_ctx", pkg, comp_lower, idx)
        render_name := fmt.tprintf("_%s_%s_%d_render", pkg, comp_lower, idx)

        // Collect variables referenced in non-snippet children for the ctx struct
        refs := collect_var_refs(g, non_snippet_children[:])

        // 1. Generate children body into temp builder with props_prefix="ctx"
        //    Save preamble so nested component preambles can be hoisted.
        preamble_before := strings.clone(strings.to_string(g.preamble))
        strings.builder_reset(&g.preamble)

        old_b := g.b
        old_indent := g.indent
        g.b = strings.Builder{}
        strings.builder_init(&g.b)
        g.indent = 1

        old_prefix := g.props_prefix
        g.props_prefix = "ctx"
        push_scope(g)
        gen_nodes(g, non_snippet_children[:], &g.b)
        pop_scope(g)
        g.props_prefix = old_prefix

        children_body := strings.clone(strings.to_string(g.b))
        g.b = old_b
        g.indent = old_indent

        // 2. Extract any nested preamble (from inner components) and hoist it
        nested_preamble := strings.clone(strings.to_string(g.preamble))
        strings.builder_reset(&g.preamble)

        // 3. Reassemble preamble: previous + nested (hoisted) + this component's ctx/proc
        strings.write_string(&g.preamble, preamble_before)
        if len(nested_preamble) > 0 {
            strings.write_string(&g.preamble, nested_preamble)
        }

        // Ctx struct
        fmt.sbprintf(&g.preamble, "%s :: struct {{\n", ctx_name)
        for ref in refs {
            field_type := props_field_type(g, ref)
            if len(field_type) == 0 { field_type = "rawptr" }
            fmt.sbprintf(&g.preamble, "    %s: %s,\n", ref, field_type)
        }
        strings.write_string(&g.preamble, "}\n\n")

        // Render proc with children body
        fmt.sbprintf(&g.preamble, "%s :: proc(w: io.Writer, ctx_ptr: rawptr) {{\n", render_name)
        if len(refs) > 0 {
            fmt.sbprintf(&g.preamble, "    ctx := (^%s)(ctx_ptr)\n", ctx_name)
        }
        strings.write_string(&g.preamble, children_body)
        strings.write_string(&g.preamble, "}\n\n")

        // 4. Emit call site: ctx initialization + component render call
        write_indent(g, b)
        fmt.sbprintf(b, "_ctx_%d := %s{{\n", idx, ctx_name)
        for ref in refs {
            resolved := resolve_ident(g, ref)
            write_indent(g, b)
            fmt.sbprintf(b, "    %s = %s,\n", ref, resolved)
        }
        write_indent(g, b)
        strings.write_string(b, "}\n")

        write_indent(g, b)
        if len(pkg) > 0 {
            fmt.sbprintf(b, "%s.render(w, %s.Props{{\n", pkg, pkg)
        } else {
            fmt.sbprintf(b, "render(w, Props{{\n")
        }

        gen_component_attrs(g, comp.attributes[:], b)

        // Children field
        write_indent(g, b)
        g.need_rt = true
        fmt.sbprintf(b, "    children = rt.Children{{\n")
        write_indent(g, b)
        fmt.sbprintf(b, "        func = %s,\n", render_name)
        write_indent(g, b)
        fmt.sbprintf(b, "        ctx = &_ctx_%d,\n", idx)
        write_indent(g, b)
        strings.write_string(b, "    },\n")

        write_indent(g, b)
        strings.write_string(b, "})\n")

    } else if has_snippet_defs {
        // Generate snippet render procs into preamble
        for sd in snippet_defs {
            render_name := fmt.tprintf("_%s_%s_%d_%s_render", pkg, comp_lower, idx, sd.name)
            param_name := ""
            param_type := ""
            if pn, ok := sd.param_name.?; ok { param_name = pn }
            if pt, ok := sd.param_type.?; ok { param_type = pt }

            // Proc signature
            if len(param_type) > 0 {
                fmt.sbprintf(&g.preamble, "%s :: proc(w: io.Writer, ctx_ptr: rawptr, %s: %s) {{\n", render_name, param_name, param_type)
            } else {
                fmt.sbprintf(&g.preamble, "%s :: proc(w: io.Writer, ctx_ptr: rawptr) {{\n", render_name)
            }

            // Generate body into temp builder
            old_b := g.b
            old_indent := g.indent
            g.b = strings.Builder{}
            strings.builder_init(&g.b)
            g.indent = 1

            push_scope(g)
            if len(param_name) > 0 {
                add_to_scope(g, param_name)
            }
            gen_nodes(g, sd.children[:], &g.b)
            pop_scope(g)

            strings.write_string(&g.preamble, strings.to_string(g.b))
            g.b = old_b
            g.indent = old_indent
            strings.write_string(&g.preamble, "}\n\n")
        }

        // Emit component call with snippet bindings
        write_indent(g, b)
        if len(pkg) > 0 {
            fmt.sbprintf(b, "%s.render(w, %s.Props{{\n", pkg, pkg)
        } else {
            fmt.sbprintf(b, "render(w, Props{{\n")
        }
        gen_component_attrs(g, comp.attributes[:], b)
        for sd in snippet_defs {
            render_name := fmt.tprintf("_%s_%s_%d_%s_render", pkg, comp_lower, idx, sd.name)
            param_type := ""
            if pt, ok := sd.param_type.?; ok {
                param_type = pt
            }
            g.need_rt = true
            write_indent(g, b)
            if len(param_type) > 0 {
                fmt.sbprintf(b, "    %s = rt.Snippet(%s){{\n", sd.name, param_type)
            } else {
                fmt.sbprintf(b, "    %s = rt.Children{{\n", sd.name)
            }
            write_indent(g, b)
            fmt.sbprintf(b, "        func = %s,\n", render_name)
            write_indent(g, b)
            strings.write_string(b, "        ctx = nil,\n")
            write_indent(g, b)
            strings.write_string(b, "    },\n")
        }
        write_indent(g, b)
        strings.write_string(b, "})\n")
    } else {
        // Self-closing or no children
        write_indent(g, b)
        if len(pkg) > 0 {
            fmt.sbprintf(b, "%s.render(w, %s.Props{{\n", pkg, pkg)
        } else {
            fmt.sbprintf(b, "render(w, Props{{\n")
        }
        gen_component_attrs(g, comp.attributes[:], b)
        write_indent(g, b)
        strings.write_string(b, "})\n")
    }
}

// Emit component attribute assignments (shared by all component branches)
gen_component_attrs :: proc(g: ^Generator, attrs: []ast.Attribute, b: ^strings.Builder) {
    for attr in attrs {
        write_indent(g, b)
        switch v in attr.value {
        case ast.Static_Value:
            fmt.sbprintf(b, "    %s = \"%s\",\n", attr.name, v.value)
        case ast.Dynamic_Value:
            expr := resolve_expr(g, v.expr)
            fmt.sbprintf(b, "    %s = %s,\n", attr.name, expr)
        case ast.Bool_Shorthand:
            fmt.sbprintf(b, "    %s = true,\n", attr.name)
        }
    }
}

// collect_var_refs collects all top-level variable references in nodes
// that are props fields (not local scope vars)
collect_var_refs :: proc(g: ^Generator, nodes: []ast.Node) -> []string {
    seen := make(map[string]bool)
    refs_dyn := make([dynamic]string)
    collect_refs_recursive(g, nodes, &seen, &refs_dyn)
    return refs_dyn[:]
}

// Try to collect a root name as a props-field reference.
// Skips keywords, literals, in-scope locals, and non-props identifiers.
maybe_collect_ref :: proc(g: ^Generator, expr: string, seen: ^map[string]bool, refs: ^[dynamic]string) {
    root := get_root_name(expr)
    if len(root) == 0 { return }
    if is_odin_keyword(root) { return }
    if root[0] >= '0' && root[0] <= '9' { return } // number literal
    if is_in_scope(g, root) { return }
    if !(root in g.props_fields) { return } // only collect actual props
    if !seen[root] {
        seen[root] = true
        append(refs, root)
    }
}

collect_refs_recursive :: proc(g: ^Generator, nodes: []ast.Node, seen: ^map[string]bool, refs: ^[dynamic]string) {
    for node in nodes {
        switch n in node {
        case ast.Text:
            // no refs
        case ast.Element:
            for attr in n.attributes {
                switch v in attr.value {
                case ast.Dynamic_Value:
                    maybe_collect_ref(g, v.expr, seen, refs)
                case ast.Static_Value, ast.Bool_Shorthand:
                    // nothing
                }
            }
            collect_refs_recursive(g, n.children[:], seen, refs)
        case ast.Expression:
            maybe_collect_ref(g, n.content, seen, refs)
        case ast.Raw_Html:
            maybe_collect_ref(g, n.content, seen, refs)
        case ast.If_Block:
            maybe_collect_ref(g, n.condition, seen, refs)
            collect_refs_recursive(g, n.children[:], seen, refs)
            if eb, ok := n.else_body.?; ok {
                collect_refs_recursive(g, eb[:], seen, refs)
            }
        case ast.Each_Block:
            maybe_collect_ref(g, n.iterable, seen, refs)
            collect_refs_recursive(g, n.children[:], seen, refs)
        case ast.Snippet_Def:
            // Don't recurse — snippet defs have their own scope/proc
        case ast.Render_Call:
            // nothing direct
        case ast.Component:
            collect_refs_recursive(g, n.children[:], seen, refs)
        }
    }
}

get_root_name :: proc(expr: string) -> string {
    trimmed := strings.trim_space(expr)
    // Strip leading unary operators
    for len(trimmed) > 0 && (trimmed[0] == '!' || trimmed[0] == '-') {
        trimmed = strings.trim_space(trimmed[1:])
    }
    // Extract first identifier token
    end := 0
    for end < len(trimmed) && is_ident_char(trimmed[end]) {
        end += 1
    }
    if end > 0 {
        return trimmed[:end]
    }
    return trimmed
}

// ─── layout inlining ──────────────────────────────────────────────────────────

// gen_layout_inlined generates code that inlines the layout chain around the
// page content. layout_chain is ordered outermost to innermost.
//
// Strategy: generate innermost content first into a string buffer, then wrap it
// in each successive layout by setting g.layout_children_content so that
// gen_render_call substitutes {@render children()} with the inner content.
//
// The result is equivalent to:
//   layout[0] wraps (layout[1] wraps (... wraps page_content))
gen_layout_inlined :: proc(g: ^Generator, page_nodes: []ast.Node, layout_chain: []ast.Document, b: ^strings.Builder) {
    if len(layout_chain) == 0 {
        gen_nodes(g, page_nodes, b)
        return
    }

    // Step 1: Generate page content into a temp buffer
    page_buf := strings.Builder{}
    strings.builder_init(&page_buf)
    gen_nodes(g, page_nodes, &page_buf)
    inner_content := strings.to_string(page_buf)

    // Step 2: Wrap with each layout from innermost to outermost
    // We iterate the chain in reverse so that we progressively wrap inner content
    for i := len(layout_chain) - 1; i >= 0; i -= 1 {
        layout := layout_chain[i]

        // Save previous children content state
        old_children := g.layout_children_content

        // Set the current inner content as what {@render children()} will emit
        g.layout_children_content = inner_content

        // Generate this layout into a temp buffer
        layout_buf := strings.Builder{}
        strings.builder_init(&layout_buf)
        gen_nodes(g, layout.children[:], &layout_buf)
        inner_content = strings.to_string(layout_buf)

        // Restore previous state
        g.layout_children_content = old_children
    }

    // Step 3: Write the final wrapped content
    strings.write_string(b, inner_content)
}

// ─── script helpers ──────────────────────────────────────────────────────────

// extract_extra_defs extracts non-import, non-Props type definitions from
// the raw script block content (e.g. custom structs used by Props fields).
extract_extra_defs :: proc(raw: string) -> string {
    result := strings.Builder{}
    strings.builder_init(&result)
    lines := strings.split(raw, "\n")
    defer delete(lines)

    i := 0
    for i < len(lines) {
        trimmed := strings.trim_space(lines[i])
        // Skip import lines
        if strings.has_prefix(trimmed, "import ") {
            i += 1
            continue
        }
        // Skip Props :: struct { ... }
        if strings.has_prefix(trimmed, "Props :: struct") {
            brace_depth := 0
            for i < len(lines) {
                for c in lines[i] {
                    if c == '{' { brace_depth += 1 }
                    if c == '}' { brace_depth -= 1 }
                }
                i += 1
                if brace_depth <= 0 { break }
            }
            continue
        }
        // Skip blank lines at the start
        if strings.builder_len(result) == 0 && len(trimmed) == 0 {
            i += 1
            continue
        }
        strings.write_string(&result, lines[i])
        strings.write_string(&result, "\n")
        i += 1
    }

    return strings.trim_space(strings.to_string(result))
}
